# Stock Plugin Configuration
# 이 파일은 주식 플러그인의 전반적인 설정을 담당합니다.

# 주식 가격이 변동되는 주기 (초 단위)
# 1초 = 20틱. 예를 들어 60으로 설정하면 60초(1분)마다 주식 가격이 변동됩니다.
update-interval-seconds: 60

# 거래 수수료 (단위: %)
# 0.5는 0.5%를 의미합니다. 0으로 설정하면 수수료가 없습니다.
# 매수 시에는 (가격 * 수량) * (1 + 수수료율) 만큼 차감됩니다.
# 매도 시에는 (가격 * 수량) * (1 - 수수료율) 만큼 지급됩니다.
transaction-fee-percent: 0.5

# 주식 가격 변동 알림 임계값 (단위: %)
# 주식 가격이 이 값 이상 변동하면 구독자에게 알림이 전송됩니다.
# 예를 들어 1.0으로 설정하면 1% 이상 가격이 변동될 때 알림이 갑니다.
notification-threshold-percent: 1.0

# 하루 1인당 주식 거래 제한 기능
stock-transaction-limits:
  enable: true # 사용 여부
  # 0으로 설정시 무한
  buy: 10 # 하루에 10번 구매가능
  sell: 10 # 하루에 10번 판매가능

# GUI 설정
gui:
  # 메인 주식 시장 GUI의 제목입니다.
  main-title: "§l주식   시장"
  # 내 주식 현황 GUI의 제목입니다.
  portfolio-title: "§l내 주식 현황"
  # 투자 순위표 GUI의 제목입니다.
  ranking-title: "§l투자 순위표"

  # 이 값이 true이면, 모든 GUI 아이템의 재료가 STRUCTURE_VOID로 대체됩니다.
  # 투명한 STRUCTURE_VOID 텍스처를 가진 커스텀 리소스 팩을 사용하는 경우에 유용합니다.
  # 이를 통해 GUI 디자인의 자유도를 높일 수 있습니다.
  items-all-structure-void: false

  # GUI 버튼 설정
  # 각 버튼의 재료, 커스텀 모델 데이터, 이름, 로어를 설정할 수 있습니다.
  buttons:
    # 포트폴리오 버튼 설정
    portfolio:
      material: PLAYER_HEAD # 아이템 재료 (예: PLAYER_HEAD, EMERALD, DIAMOND)
      custom-model-data: 0 # 커스텀 모델 데이터 (리소스 팩 사용 시 유용)
      name: "§a내 주식 현황" # 버튼 이름
      lore: # 버튼 설명 (여러 줄 가능)
        - "§7클릭하여 내 주식 정보를 봅니다."
    # 랭킹 버튼 설정
    ranking:
      material: EMERALD # 아이템 재료
      custom-model-data: 0 # 커스텀 모델 데이터
      name: "§b투자 순위표" # 버튼 이름
      lore: # 버튼 설명
        - "§7클릭하여 투자 순위를 봅니다."